### ISSUE TITLE
Move partitions elsewhere

### ISSUE THREAD

**Issue by n28div** [andreamust/MusicMetaLinker#1]
Repository is huge with the ChoCo partitions included. I think it would be best to move them to another repository and maintain this one as a library for music entity linking.

**Comment by andreamust** [comment]
The idea is to unbundle the repository in two:
- `MusicMetaLinker`: extracts and aligns metadata
- `SmasHubLinker` (within the SmasHub organization): uses MusicMetaLinker and adapts the workflow to the SmasHub JAMS-based workflow.

For now, I am creating a new branch for keeping a copy of the generated partitions, and removing them from main.

**Comment by andreamust** [comment]
> The idea is to unbundle the repository in two:
> 
> * `MusicMetaLinker`: extracts and aligns metadata
> * `SmasHubLinker` (within the SmasHub organization): uses MusicMetaLinker and adapts the workflow to the SmasHub JAMS-based workflow.
> 
> For now, I am creating a new branch for keeping a copy of the generated partitions, and removing them from main.

Done

**Comment by n28div** [comment]
Great, I think installing through pip will still download the partitions as well, but as soon as they will be out of the repo it won't be a problem

Edit:
Just tried, it does not download anything else. Closing the issue.
